// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK1Qu1fGA3xSkKqHDGtShu7ZE6FczHP8Q',
    appId: '1:515838664309:web:cb71126b1f5ae57f92a23c',
    messagingSenderId: '515838664309',
    projectId: 'women-safety-fa8e0',
    authDomain: 'women-safety-fa8e0.firebaseapp.com',
    storageBucket: 'women-safety-fa8e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVDCHZ07YdruNZb_yDY0AbDGdyrM3sPac',
    appId: '1:515838664309:android:6af22452f61945a692a23c',
    messagingSenderId: '515838664309',
    projectId: 'women-safety-fa8e0',
    storageBucket: 'women-safety-fa8e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6M9Lc8b5QZGKaHiX7YolNoj92MUHYG5M',
    appId: '1:515838664309:ios:8b6251498bb1a30b92a23c',
    messagingSenderId: '515838664309',
    projectId: 'women-safety-fa8e0',
    storageBucket: 'women-safety-fa8e0.appspot.com',
    iosBundleId: 'com.example.megaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6M9Lc8b5QZGKaHiX7YolNoj92MUHYG5M',
    appId: '1:515838664309:ios:8b6251498bb1a30b92a23c',
    messagingSenderId: '515838664309',
    projectId: 'women-safety-fa8e0',
    storageBucket: 'women-safety-fa8e0.appspot.com',
    iosBundleId: 'com.example.megaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK1Qu1fGA3xSkKqHDGtShu7ZE6FczHP8Q',
    appId: '1:515838664309:web:55d804dc0efcadd492a23c',
    messagingSenderId: '515838664309',
    projectId: 'women-safety-fa8e0',
    authDomain: 'women-safety-fa8e0.firebaseapp.com',
    storageBucket: 'women-safety-fa8e0.appspot.com',
  );
}
